name: ${project.artifactId}
main: com.mcmiddleearth.mcme.rpgtree.RPGTree
version: ${project.version}
authors: [NicoviçTheSixth]
depend: [FastAsyncWorldEdit]
api-version: 1.16

commands:
  RPGTree:
    description: Use to create trees, treetypes and frames
    usage: /rpgt <subcommand>